# Generated by Django 4.2.5 on 2023-09-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('configure1', models.CharField(max_length=100)),
                ('configure2', models.CharField(max_length=100)),
                ('configure3', models.CharField(max_length=100)),
                ('configure4', models.CharField(max_length=100)),
                ('configure5', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
